-- Packer
require('plugins')
-- Config
require('settings')
require('settings.color')
require('settings.completion')
require('settings.filetype')
-- LSP Config
require('lsp')
require('plugins.lint')
-- Plugins config
require('plugins.feline')
-- require('plugins.fterm')
require('plugins.floaterm')
require('plugins.hlslens')
require('plugins.treesitter')
require('plugins.colorizer')
require('plugins.gitsigns')
require('plugins.nvim-autopairs')
require('plugins.nvim-ts-rainbow')
require('plugins.nvimtree')
require('plugins.rnvimr')
require('plugins.indent-blankline')
require('plugins.telescope')
require('plugins.numb')
require('plugins.vim-startify')
require('plugins.ctrlsf')
require('plugins.vista')
-- require('plugins.editorconfig')
-- require('plugins.vim-gutentags')
require('plugins.vim-rooter')
require('plugins.vim-rubocop')
require('plugins.vim-signature')
require('plugins.vim-sneak')
require('plugins.lspkind')
-- require('plugins.neoscroll')
require('plugins.smoothie')
-- require('plugins.minimap')
-- Keymap
require('settings.keymap')
